set1 = {1,2,3,4}
set2 = { 1,2,3,4 }

# print(set1.union(set2))
# print(set1.intersection(set2))
# print(set1.difference(set2))
# print(set1.discard(3))
# print(set1.update(set2))
# print(set1.add(6))
# print(set1.remove(6))
# print(set1.isdisjoint(set2))
print(set1.symmetric_difference(set2))
# print(set2)
# print(len(set2))
# print(2 in set1)
set1.symmetric_difference_update(set2)
print(set1)
# print (set1)
print(set1.issubset(set2))
print(set1.issuperset(set2))
